# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20160422_1217'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='ask_profiles',
        ),
        migrations.AlterModelTable(
            name='question',
            table='ask_questions',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='ask_tags',
        ),
    ]
