# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ask', '0004_auto_20160422_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'ask_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('rating', models.IntegerField()),
                ('tags', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ask_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ask_tags',
            },
        ),
    ]
