# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20160423_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
