# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20160425_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Answer'),
        ),
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
    ]
