# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20160425_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
