# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_auto_20160429_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
