# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_auto_20160510_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='avatar.png', upload_to=''),
        ),
    ]
