# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0015_auto_20160510_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
