# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_auto_20160611_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_at']},
        ),
    ]
