# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0018_auto_20160611_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(to='ask.Like'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(to='ask.Like'),
        ),
    ]
