# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0020_auto_20160612_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
