# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 08:41
from __future__ import unicode_literals

import ask.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0022_auto_20160612_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=ask.models.LikesField(blank=True, to='ask.Like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=ask.models.LikesField(blank=True, to='ask.Like'),
        ),
    ]
