# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0023_auto_20160613_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, to='ask.Like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, to='ask.Like'),
        ),
    ]
